# .github/workflows/daily-jsonl-move.yml
name: Daily JSONL Move (Python)

on:
  schedule:
    - cron: '0 1 * * *'  # every day at 08:00 UTC
  workflow_dispatch:

jobs:
  move-jsonl-item:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run Python script to update word of the day
        run: |
          python move_item.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add data.jsonl index.json today.json past.csv
          git commit -m "chore: move one JSONL item [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
